export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  DASHBOARD_ADMIN: '/dashboard/admin',
  DASHBOARD_WRITERS: '/dashboard/writers',
  DASHBOARD_WRITER: '/dashboard/writer',
  DASHBOARD_WRITER_ADD: '/dashboard/writer/add',
  DASHBOARD_NEWS_CREATE: '/dashboard/news/create',
  DASHBOARD_NEWS: '/dashboard/news',
  DASHBOARD_PROFILE: '/dashboard/profile',
  DASHBOARD_UNABLE_ACCESS: '/dashboard/unable-access',
  UNABLE_ACCESS: 'unable-access',
  PROFILE: 'profile',
  NEWS: 'news',
  ADMIN: 'admin',
  WRITER_ADD: 'writer/add',
  WRITERS: 'writers',
  WRITER_EDIT: 'writer/edit/:id',
  WRITER: 'writer',
  NEWS_CREATE: 'news/create',
  NEWS_EDIT: 'news/edit/:newsId',
}
